kind: pipeline
type: docker
name: default

steps:
- name: clone
  image: plugins/git
  settings:
    tags: true

- name: build_and_run_docker_compose
  image: docker:19.03.12
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
    - docker-compose up --build -d

- name: run_test_create_resource
  image: docker:19.03.12
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
    - docker-compose exec -T web pytest tests/test_create_resource.py || (docker-compose logs web && exit 1)

- name: run_test_delete_resource
  image: docker:19.03.12
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
    - docker-compose exec -T web pytest tests/test_delete_resource.py

- name: run_test_get_resource
  image: docker:19.03.12
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
    - docker-compose exec -T web pytest tests/test_get_resource.py

- name: run_test_update_resource
  image: docker:19.03.12
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
    - docker-compose exec -T web pytest tests/test_update_resource.py

- name: teardown
  image: docker:19.03.12
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
    - docker-compose down -v

# - name: ansible_ssh
#   image: williamyeh/ansible:alpine3
#   commands:
#     - ansible -i /ansible_demo/inventory.ini all -m ping

# - name: ansible_deploy
#   image: williamyeh/ansible:alpine3
#   commands:
#     - ansible-playbook -i /ansible_demo/inventory.ini /ansible_demo/deploy.yml --extra-vars "selected_repo=flask-demo"

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
    - push
    - pull_request
