kind: pipeline
name: default

steps:
- name: run
  image: docker/compose:1.29.1
  privileged: true
  commands:
    - docker-compose -f docker-compose.yaml up -d
  volumes:
    - name: dockersock
      path: /var/run/docker.sock

volumes:
- name: dockersock