kind: pipeline
type: docker
name: dev

steps:
  - name: build-and-run
    image: docker/compose:1.29.2
    environment:
      COMPOSE_FILE: docker-compose.yaml
    commands:
      - docker-compose up --build -d

  - name: run-tests
    image: docker/compose:1.29.2
    commands:
      - docker-compose exec -T web pytest tests/test_create_resource.py || (docker-compose logs web && exit 1)
      - docker-compose exec -T web pytest tests/test_delete_resource.py
      - docker-compose exec -T web pytest tests/test_get_resource.py
      - docker-compose exec -T web pytest tests/test_update_resource.py

  - name: teardown
    image: docker/compose:1.29.2
    commands:
      - docker-compose down -v

services:
  docker:
    image: docker:dind
    privileged: true

trigger:
  event:
    - push
    - pull_request
