version: '3'
services:
  web:
    image: a607ernie/flask-demo:latest
    container_name: flask-demo_app
    volumes:
      - ./app:/app
      - ./tests:/app/tests
      - shared_data:/app
    command: gunicorn --workers=3 --bind=0.0.0.0:5001 wsgi:app
    environment:
      - FLASK_APP=app.py
    expose:
      - "5001"
      
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: flask-demo_nginx
    ports:
      - "5002:5002"
    depends_on:
      - web
