version: '3'
services:
  web:
    build: .
    volumes:
      - ./app:/app
      - ./tests:/tests

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: flask-demo_nginx
    ports:
      - "5002:5002"
    depends_on:
      - web
