version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask-demo_app
    # volumes:
    #   # - ./app:/app
    #   # - ./tests:/tests
    #   - ./:/app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: flask-demo_nginx
    ports:
      - "5002:5002"
    depends_on:
      - web
