version: '3'
services:
  web:
    build: .
    volumes:
      - ./app:/app
      - ./tests:/tests

  nginx:
    image: nginx:latest
    ports:
      - "5002:5002"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
