version: '3'
services:
  web:
    image: a607ernie/flask-demo:latest
    container_name: flask-demo_app
    volumes:
      - ./app:/app
      - ./tests:/app/tests

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: flask-demo_nginx
    ports:
      - "5002:5002"
    depends_on:
      - web
